// 1. GET to all the records from products
GET http://localhost:5050/products

###

// 2. GET all the prices under 50 from products
GET http://localhost:5050/products/price

###

// Before: GET users
GET http://localhost:5050/users

###

// 3. GET all usernames and emails from users
GET http://localhost:5050/users/email-username

###

// 4. GET all orders in a descending order
GET http://localhost:5050/orders

###

// 5. GET all products with a price greater than 50 and belongs to Electronics category
GET http://localhost:5050/product/price-category

###

// 6. GET all post that includes the word "tutorial"
GET http://localhost:5050/post/tutorial

###