// 1. GET to all the records from products
GET http://localhost:5050/products

###

// 2. GET all the prices under 50 from products
GET http://localhost:5050/products/price

###

// Before: GET users
GET http://localhost:5050/users

###

// 3. GET all usernames and emails from users
GET http://localhost:5050/users/email-username

###

// 4. GET all orders in a descending order
GET http://localhost:5050/orders

###

// 6. GET all products with a price greater than 50 and belongs to Electronics category
GET http://localhost:5050/product/price-category

###

// 7. GET all post that includes the word "tutorial"
GET http://localhost:5050/post/tutorial

###

// 8. GET all fist 10 products from products"
GET http://localhost:5050/products/first10products

###

// 9. GET all products from a specific user
GET http://localhost:5050/products/by-user?user_id=5aa70cb7-c0ee-483b-a95d-8526d154a8a0

###